# Site
repository: KaramGhanem/KaramGhanem.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)
favicon: assets/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Karam Ghanem
title: AI Researcher & Engineer
email: ghanemkaram12@gmail.com
# email_title: Email (Email title override)
#phone: (647) 675-7443
# phone_title: Phone (Phone title override)
#website: https://scholar.google.com/citations?user=uaWuP84AAAAJ&hl=en
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  KaramGhanem
#tackstackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: karam-ghanem-b8a97a149
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
orcid_username: 0000-0001-7340-0855
googlescholar_username: ghanemkaram12@gmail.com

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  <mark>Update May 2025</mark>: I am looking for work at the intersection of AI research and impact-focused engineering, where I can apply my experience in conversational agents, large language models, and cognitively-informed machine learning to build systems that are not only intelligent, but responsible, transparent, and human-aligned.<br><br>
  
  <mark>About me</mark>:  I work on building AI systems that are aligned with human goals, values, and social contexts has been a central theme of my graduate work and industry research. I’ve led efforts across academia and industry on large language model fine-tuning, agentic architectures, and medical AI. My work emphasizes practical alignment, designing AI that adapts to human intent and context, while contributing to robust technical foundations including reinforcement learning with human feedback (RLHF), self-critique, retrieval-augmented generation (RAG), and multimodal representation learning. I’m especially interested in how humans interact with intelligent systems, and how design choices shape trust, usability, and social dynamics in real-world settings.
  I recently completed a Master’s of Engineering (Thesis) at Mila Quebec AI Institute & McGill University, where I focused on applying generative models and dimensionality reduction techniques to brain imaging and genomics. I am currently a Senior ML Engineer at Braxted Group, where I design multi-agent conversational systems for immigration services. In my previous role at ServiceNow, I contributed to the development of the TapeAgents framework and advanced large language model fine-tuning pipelines using self-critique strategies and prompt optimization. Previously, I worked in firmware and optical software testing at Infinera (now Nokia), and co-founded an engineering consultancy, bridging software, hardware, and client operations. I also had the opportunity to work on semiconductor and solar cell research under Dr. Ray LaPierre.<br><br>

  <mark>Topics of interest</mark>: Responsible AI, human-AI interaction, multi-agent systems, generative models (diffusion, transformer-based), cognitive modeling, explainability, trust in AI, personalized and goal-driven agents, and applications of AI in health, law, and public systems. <br><br>
  
  <mark>Past Works</mark> LLMs & Agent Architectures: TapeAgents, WebAgents, Form-Filling and Retrieval Agents using LangChain, DSPy, and RLHF pipelines - Biomedical AI: Linking high-dimensional brain imaging and genomics using dimensionality reduction and transformer fine-tuning. <br><br>

  <mark>Currently</mark> Working on a series of projects reflecting on the long-term implications of AI on human identity, cognition, and social systems.

#- Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Projects # Title for the section
    layout: list
    content: |
      <ul>
        {% for pub in site.publications %}
          <li>
            <a href="{{ pub.url | relative_url }}">{{ pub.title }}</a><br>
            <small>{{ pub.authors }} — {{ pub.journal }}, {{ pub.year }}</small>
          </li>
        {% endfor %}
      </ul>
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Braxted Group | AI and Knowledge Team
        sub_title: Senior ML Engineer
        caption: November 2024 – Present
        description: |
          - Created a chat history data generator that creates synthetic chat history data which is representative of user-agent interactions within an Immigration chatbot servicing system using Reddit data.
          - Utilized clustering and NLP methods like phrase mining to perform topic extraction from chat history for downstream recommendation tasks.
          - Developed a clustering system that uses extracted user data post-interaction to identify behavioral patterns, improve personalization, and enhance response accuracy.
          - Built a hybrid collaborative/content-based recommender system for personalized article recommendation.
          - Developed a Form Filling Agent that dynamically extracts, stores, and updates structured user profiles based on customizable schemas, enabling context-aware handoffs to specialized sub-agents for seamless user servicing.
          - Integrated a WebAgent using BrowserBase into a conversational AI system to autonomously retrieve and inject real-time web content when RAG confidence was low, enhancing response accuracy and maintaining seamless user interaction.
          - Designed the WebAgent to operate contextually within multi-turn conversations, enabling it to resolve references to previously mentioned topics and convert natural language queries into accurate web browsing tasks using conversational memory.
          - Architected a multi-agent system integrating a Form Filling Agent, RAG Agent, Web Agent and Conversational Agent to manage contextual understanding, document retrieval, response generation, and user servicing through intelligent routing.

      - layout: right
        title: ServiceNow Research | CAT team
        sub_title: Visiting Researcher
        caption: April 2024 – October 2024
        description: |
          - Enhanced virtual agents by fine-tuning open-source LLMs (Llama, WizardLM, Mixtral) using an RLHF loop.
          - Refined synthetic training data quality by defining agent thoughts and actions in agent dialogue with user.
          - Created and tested prompts for form-filling teacher agents using techniques like chain-of-thought, multi-step prompts, self-critique, intent discovery and by using prompt optimizers implemented with DSPy.
          - Distilled teacher agent knowledge into a more efficient smaller student model then used an RLHF loop to enhance student model performance with a critique annotator agent.
          - Used optimization techniques to significantly boost the accuracy and precision of annotator agents by 20-30% across evaluation traits, achieving the same performance as human annotators.
          - See the [TapeAgents publication](https://www.servicenow.com/research/TapeAgentsFramework.pdf) for more details.

      - layout: right
        title: Mila Quebec AI Institute & McGill University
        sub_title: Data Scientist (Contract)
        caption: January 2022 – August 2022
        description: |
          - Conducted comprehensive performance analysis of diffusion models, establishing reliable comparison frameworks across different model architectures, sampling methods, and classifier guidance.
          - Optimized diffusion model training convergence speeds while maintaining sample quality for image generation tasks.
          - Collaborated with medical professionals to align PCA-related models with domain-specific requirements, revealing novel brain-behavior correlations in high-dimensional MRI datasets.
          - Applied dimensionality reduction models to successfully predict key covarying brain features with strong statistical confidence, in medical datasets with limited sample sizes (<20 p / 1450 n).
          - Fine-tuned GFMs like HyenaDNA to enhance gene expression prediction accuracy by using the fine-tuned transformer embeddings with an independent classifier.

      - layout: right
        title: Infinera (Now Nokia) | Digital ASICs Department
        sub_title: Firmware Development Consultant
        caption: November 2019 – September 2020 | March 2021- December 2021
        description: |
          - Consulted with customers and engineers from various departments to gather feedback and requirements, ensuring firmware updates and FPGA images met specific client needs, resulting in a reduction in post-deployment issues.
          - Conceptualized system design, upgraded, maintained, and debugged firmware, FPGA, and hardware through written test scripts for fail-proof deployment which resulted in enhanced customer satisfaction.
          - Lead the development of software product testing frameworks to automate overnight firmware testing using Jenkins, which sped up firmware deployment process to customers by 50%.
      - layout: right
        title: Infinera (Now Nokia) | Optical Design Team
        sub_title: Software Engineer
        caption: May 2019 - November 2019
        description: |
          - Consulted with optical line engineers to gather insights and ensure alignment of software functions with operational needs.
          - Tested components of optical signal processing units with developed data analysis python GUI tools.
          - Developed statistical and data analysis tools to enhance optical signal processing in testing systems in addition to designing complementary UI tools for signal property visualization, achieving 86% diagnostic accuracy.
      - layout: right
        title: GE Technical Consulting Solutions (Inactive)
        sub_title: Senior Technical Consultant & Cofounder
        caption: September 2020 – December 2021
        description: |
          - Co-founded and led a multidisciplinary engineering consulting firm, overseeing projects requiring expertise in mechanical, electrical, and software engineering.
          - Managed company finances, including budgeting and forecasting, while successfully negotiating contracts and maintaining strong client and vendor relationships.
          - Consulted clients to identify project requirements and led a team of 6 engineers, delivering more than 3 successful projects within the first year, consistently exceeding client expectations.
      - layout: right
        title: McMaster University
        sub_title: Research Assistant
        caption: May 2018 - August 2018
        description: |
          - Conducted extensive data analysis with MCMC methods on data acquired using optical equipment.
          - Incorporated ResNet for image recognition to detect irregular surfaces on newly etched semiconductor wafers.
          - Leveraged designed experimental framework to develop an optimized reactive ion etching formula that increased semiconductor conductivity by 7%.
  - title: Education
    layout: list
    content:
      - layout: left
        title: Mila Quebec AI Institute & McGill University
        caption: September 2022 – April 2024
        description: |
          Major in Biological & Biomedical Engineering

          **Awards:**
          - Mitacs Accelerate Fellowship Award: A prestigious and highly competitive award, granted to select graduate students for exceptional research potential and academic excellence.
          - McGill Graduate Excellence Award: offered to a limited number of graduate students whose profiles are of an exceptional caliber.
      - layout: left
        title: McMaster University
        sub_title: Bachelor of Engineering
        caption: September 2016 - April 2021
        description: |
          Major in Engineering Physics  
          Honors: Summa Cum Laude

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]

collections:
  publications:
    output: true
    permalink: /publications/:name/
